.data
	pergunta: .asciiz "Digite umn número:" #DESIGNA UM VALOR ASCII PARA A VARIAVEL PERGUNTA
	par: .asciiz "É par!" #DESIGNA UM VALOR ASCII PARA A VARIAVEL PAR
	impar: .asciiz "É impar!" #DESIGNA UM VALOR ASCII PARA A VARIAVEL IMPAR
.text

la $v0, 4 #PREPARA O PROGRAMA PARA ESCREVER UMA STRING
la $a0, pergunta #DESIGNA A STRING QUE DEVE SER LIDA
syscall #IMPRIME A STRING NO PROGRAMA
la $v0, 5 #PREPARA O PROGRAMA PARA LER UM INTEIRO
syscall #SOLICITA A DIGITAÇÃO DE UM INTEIRO
move $s0,$v0 #MOVE O NÚMERO DIGITADO PARA O ESPAÇO $S0
li $s1, 2 #DESIGNA UM INT PARA O ESPAÇO $S1
li $s3, 0 #DESIGNA UM INT PARA O ESPAÇO $S3
divu $s0,$s1 #DIVIDE $S0 POR $S1, JOGANDO O RESULTADO PARA LO E O RESTO PARA HI
mfhi $s2 #MOVE O CONTEÚDO DE HI PARA $S2
beq $s3,$s2,parzin #COMPARA O CONTEÚDO DE $S3 COM $S2. SE IGUAL, PULA PARA A INSTRUÇÃO DE LABEL PAR
la $v0, 4 #PREPARA O PROGRAMA PARA ESCREVER UMA STRING
la $a0, impar #DESIGNA A STRING QUE DEVE SER LIDA
syscall #IMPRIME A STRING NO PROGRAMA
la $v0, 10 #PREPARA O PROGRAMA COM A INSTRUÇÃO DE SAIR
syscall #SAI DO PROGRAMA
parzin:la $v0, 4 #PREPARA O PROGRAMA PARA ESCREVER UMA STRING
la $a0, par #DESIGNA A STRING QUE DEVE SER LIDA
syscall #IMPRIME A STRING NO PROGRAMA